#!/usr/bin/env node
import fs from 'node:fs';import path from 'node:path';import zlib from 'node:zlib';import crypto from 'node:crypto';const ROOT=process.cwd(),idx=JSON.parse(fs.readFileSync(path.join(ROOT,'data/authority_scale/fanout_100k/index.json'),'utf8')),cfg=JSON.parse(fs.readFileSync(path.join(ROOT,'data/authority_scale/fanout_dimensions.json'),'utf8')),areas=JSON.parse(fs.readFileSync(path.join(ROOT,'data/service_areas/areas.json'),'utf8')).areas.map(x=>x.replace(',',''));const errors=[],ids=new Set(),queries=new Set(),allowedGeo=new Set(areas);let count=0;
for(const sh of idx.shards||[]){const p=path.join(ROOT,sh.path);if(!fs.existsSync(p)){errors.push(`missing_shard:${sh.path}`);continue;}const raw=fs.readFileSync(p),h=crypto.createHash('sha256').update(raw).digest('hex');if(h!==sh.sha256)errors.push(`sha_mismatch:${sh.path}`);const txt=zlib.gunzipSync(raw).toString('utf8').trim();for(const line of txt?txt.split(/\n/):[]){const r=JSON.parse(line);count++;if(ids.has(r.opportunity_id))errors.push(`duplicate_id:${r.opportunity_id}`);ids.add(r.opportunity_id);if(queries.has(r.query))errors.push(`duplicate_query:${r.query}`);queries.add(r.query);if(!allowedGeo.has(r.geography))errors.push(`undeclared_geography:${r.geography}`);if(r.disposition!=='OPPORTUNITY_ONLY')errors.push(`wrong_disposition:${r.opportunity_id}`);}}
// `count !== 100000` used to be an error, and `materialized_reference_runway`
// had to equal 100000 exactly. That is a target count enforced as a contract
// check: the only way to satisfy it is to keep exactly one hundred thousand
// cartesian strings materialized, whatever the real opportunity space happens
// to be. What is worth asserting is that the index does not lie about its own
// size and that every record is opportunity-only, both of which are checked
// above and below without naming a number.
if(idx.materialized_reference_runway!==count)errors.push(`index_claims_${idx.materialized_reference_runway}_records_found_${count}`);if(!(count>0))errors.push('no_records_materialized');if(idx.page_quota!==false)errors.push('page_quota_truth');if(cfg.repo!=='p-n-p')errors.push('wrong_repo_config');console.log(JSON.stringify({ok:!errors.length,records:count,unique_queries:queries.size,shards:(idx.shards||[]).length,theoretical_capacity:idx.theoretical_combinations,errors:errors.slice(0,30)},null,2));if(errors.length)process.exit(1);
